//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReSharperFormatOnSave.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Compatibility_UseReSharperSilentCleanup {
            get {
                return ((bool)(this["Compatibility_UseReSharperSilentCleanup"]));
            }
            set {
                this["Compatibility_UseReSharperSilentCleanup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_ExclusionExpression {
            get {
                return ((string)(this["Cleaning_ExclusionExpression"]));
            }
            set {
                this["Cleaning_ExclusionExpression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_UseUndoTransactions {
            get {
                return ((bool)(this["General_UseUndoTransactions"]));
            }
            set {
                this["General_UseUndoTransactions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_SkipUndoTransactionsDuringAutoCleanupOnSave {
            get {
                return ((bool)(this["General_SkipUndoTransactionsDuringAutoCleanupOnSave"]));
            }
            set {
                this["General_SkipUndoTransactionsDuringAutoCleanupOnSave"] = value;
            }
        }
    }
}
